### ISSUE TITLE
Support NS (2) record_type

### ISSUE THREAD

**Issue by jleopold28** [ultradns/terraform-provider-ultradns#12]
I am attempting to upgrade from [hashicorp/terraform-provider-ultradns](https://github.com/hashicorp/terraform-provider-ultradns) to `ultradns/terraform-provider-ultradns` and I am unable to create records with the `NS` type. 

Example code:
```
resource "ultradns_record" "delegation" {
  zone_name = "my_zone.com."
  owner_name = aws_route53_zone.default.name
  record_data = formatlist("%s.", aws_route53_zone.default.name_servers)
  record_type = "NS"
  ttl   = 14400
}
 ```
 
 Fails with:
 ```
 Error: invalid or unsupported record type 

   with ultradns_record.delegation,
   on dns_delegation.tf line 5, in resource "ultradns_record" "delegation":
    5:   record_type = "NS"
```

Can `NS` be added as a supported record type?

Thanks

**Comment by stevedejong** [comment]
@jleopold28 - thanks for the feedback.

Yes! we will certainly be adding support for creation of additional NS records in upcoming releases.
